name: Lint, Build, Test and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - task/fork-playwright

  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  BRANCH_NAME: GITHUB_REF#refs/heads/

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-latest

    steps:
      - name: Trigger external worfkflow
        uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: Onokaev
          repo: ms-graph-tester-v1
          workflow_file_name: run-playwright-test.yml
          ref: master
          github_token: ${{ secrets.ACCESS_TOKEN }}
          wait_workflow: true
          client_payload: '{ "branchName": "${{ env.BRANCH_NAME }}" }'